# docker-compose.yml
version: '3.8'
services:
  application:
    build: .
    ports:
      - '80:5000'
    environment:
      NEO4J_HOST: database
    env_file:
      - 'docker_env_genetta'
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
  database:
    image: neo4j:5.7
    env_file:
      - 'docker_env_neo4j'
    volumes:
      - dbdata:/data
    ports:
      - '7474:7474'
      - '7687:7687'
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 30
      start_period: 5s
      
volumes:
  dbdata: